apiVersion: v2
name: pedido-app
version: 1.0.0
type: application

dependencies:
  - name: postgresql
    version: 15.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: db
    condition: db.enabled
