global:
  nameOverride: ""
  fullnameOverride: ""

db:
  enabled: true
  auth:
    existingSecret: ""    # si lo dejas vacío, se crea el Secret anterior
    password: "pedidos123"
    username: "postgres"
    database: "postgres"
  primary:
    persistence:
      enabled: true
      size: 1Gi
  resources:
    requests: { cpu: "50m", memory: "128Mi" }
    limits:   { cpu: "200m", memory: "256Mi" }

app:
  image:
    repository: ritatrcr/delivery-app
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
  replicas: 1
  containerPort: 3000
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "300m", memory: "256Mi" }

  env:
    NODE_ENV: production
    DB_HOST: "{{ include \"pedido-app.dbHost\" . }}"
    DB_PORT: "5432"
    DB_NAME: "postgres"
    DB_USER: "postgres"
  secretRefs:
    useDbSecret: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix
  rewriteTarget: /
  tls: []

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
