# === GLOBALS ===
global:
  host: "app.local"     # override en dev/prod
  pathPrefix: "/"       # si usas prefijos, cámbialo

# === APP (subchart) ===
app:
  enabled: true
  image:
    repository: ritatrcr/delivery-app
    tag: v1.0.7
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 75

  # Variables NO sensibles -> van a ConfigMap
  config:
    NODE_ENV: "production"
    DB_HOST: ""            # si lo dejas vacío, lo calculamos al vuelo: <release>-postgresql
    DB_PORT: "5432"
    DB_NAME: "pedidos"

  # Variables sensibles -> van a Secret
  secret:
    DB_USER: "pedidos"
    DB_PASSWORD: "pedidos123"

# === PostgreSQL (Bitnami) ===
postgres:
  enabled: true
postgresql:
  architecture: standalone

  auth:
    username: pedidos
    password: pedidos123
    database: pedidos
    

  primary:
    persistence:
      enabled: true
      size: 8Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
