global:
  host: dev.167.172.14.0.nip.io
  pathPrefix: "/"

app:
  image:
    tag: v1.0.4
  replicas: 1
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "300m", memory: "256Mi" }
  config:
    NODE_ENV: development

postgresql:
  primary:
    persistence:
      size: 4Gi
