ingress:
  className: nginx
  host: dev.tu-dominio.local

app:
  image:
    repository: ritatrcr/delivery-app   # tu imagen unificada
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    port: 3000                         # expuesto por tu monolito
  resources:
    requests: { cpu: "200m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }
  env:                                  # no sensibles
    NODE_ENV: production
    DB_HOST: "{{ .Release.Name }}-db-postgresql"
    DB_PORT: "5432"
    DB_NAME: "pedidos"
  secret:
    usernameKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD

db:
  enabled: true
  auth:
    username: pedidos
    password: cambia-en-prod
    database: pedidos
  primary:
    persistence:
      enabled: true
      size: 8Gi
