app:
  image:
    repository: ritatrcr/delivery-app
    tag: v1.0.22
  replicas: 2
  env:
    NODE_ENV: development
    DB_HOST: "{{ include \"pedido-app.dbHost\" . }}"
    DB_PORT: "5432"
    DB_NAME: "pedidos"
    DB_USER: "pedidos"
    DB_PASSWORD: "pedidos123"   # o quítalo si lo montas solo por Secret
service:
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  className: nginx
  host: dev.167.172.14.0.nip.io
  path: /
db:
  enabled: true
  auth:
    existingSecret: "pedido-dev-db-credentials"
  primary:
    persistence:
      enabled: true
      size: 1Gi
