apiVersion: v1
kind: Service
metadata:
  name: delivery-app
  labels:
    app: delivery-app
spec:
  type: ClusterIP
  selector:
    app: delivery-app
  ports:
    - name: http
      port: 80      # Puerto interno del Service
      targetPort: 3000  # Puerto del contenedor
      protocol: TCP
