apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: bd-secret  

        env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: bd-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bd-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bd-secret
                  key: POSTGRES_PASSWORD


            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

              volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

        volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pvc  # Asegúrate de que el PVC coincida
