apiVersion: v1
kind: Secret
metadata:
  name: bd-secret
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
