          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: APP_PORT
              value: "{{ .Values.service.targetPort }}"
            - name: HOST
              value: "0.0.0.0"
            # ... DB_* ...

          # Probes (readiness por TCP para “levantar” endpoints)
          startupProbe:
            httpGet:
              path: {{ .Values.healthPath | quote }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.healthPath | quote }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
