app:
  image:
    repository: TU_USER/delivery-app
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  replicas: 2
  service:
    port: 3000
  resources:
    requests: { cpu: "200m", memory: "256Mi" }
    limits:   { cpu: "500m", memory: "512Mi" }

  # ⬇⬇ AQUÍ va tu HPA (values) ⬇⬇
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 100
            periodSeconds: 60
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 4
            periodSeconds: 15
