image:
  repository: ritatrcr/delivery-app
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 75

config:
  NODE_ENV: development
  DB_HOST: ""
  DB_PORT: "5432"
  DB_NAME: "pedidos"

secret:
  DB_USER: "pedidos"
  DB_PASSWORD: "pedidos123"
