apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pedido-app.fullname" . }}-config
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ default "production" .Values.app.env.NODE_ENV | quote }}
  DB_HOST:  {{ required "app.env.DB_HOST is required"  .Values.app.env.DB_HOST  | quote }}
  DB_PORT:  {{ required "app.env.DB_PORT is required"  .Values.app.env.DB_PORT  | quote }}
  DB_NAME:  {{ required "app.env.DB_NAME is required"  .Values.app.env.DB_NAME  | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pedido-app.fullname" . }}-secret
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER:     {{ required "app.env.DB_USER is required" .Values.app.env.DB_USER | quote }}
  DB_PASSWORD: {{ required "app.env.DB_PASSWORD is required" .Values.app.env.DB_PASSWORD | quote }}
