apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  LOG_LEVEL: "{{ .Values.config.LOG_LEVEL }}"
  FEATURE_X_ENABLED: "{{ .Values.config.FEATURE_X_ENABLED }}"
