apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  # Si no viene DB_HOST, usar el nombre del svc del chart de bitnami
  DB_HOST: {{ default (printf "%s-postgresql" .Release.Name) .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
