apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.auth.existingSecret | default (printf "%s-db-credentials" (include "pedido-app.fullname" .)) }}
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.db.auth.password | default "pedidos123" | quote }}
  postgres-password: {{ .Values.db.auth.password | default "pedidos123" | quote }}
