apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "app.fullname" . }}-secret
stringData:
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
