apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
stringData:
  DB_USER: {{ required "app.secret.DB_USER is required" .Values.app.secret.DB_USER | quote }}
  DB_PASSWORD: {{ required "app.secret.DB_PASSWORD is required" .Values.app.secret.DB_PASSWORD | quote }}

  # Si usas Bitnami PostgreSQL con auth.existingSecret:
  password: {{ .Values.app.secret.DB_PASSWORD | quote }}