apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc }}
  DB_NAME: {{ .Values.postgres.db | b64enc }}
  DB_HOST: {{ "postgres-service" | b64enc }}
  DB_PORT: {{ .Values.postgres.port | toString | b64enc }}

  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
