apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patrones
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://ritatrcr.github.io/helm-chart/
    chart: patrones
    targetRevision: "*"  
    helm:
      valueFiles:
        - values.yaml
      parameters: []  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
