      - name: Bump Chart version (patch) and appVersion (optional)
        shell: bash
        run: |
          set -euxo pipefail
          cd "$CHART_DIR"
          # Lee versión actual y súbele el patch (0.1.0 -> 0.1.1)
          CUR=$(yq '.version' Chart.yaml)
          MAJOR=$(echo "$CUR" | cut -d. -f1)
          MINOR=$(echo "$CUR" | cut -d. -f2)
          PATCH=$(echo "$CUR" | cut -d. -f3)
          NEXT="${MAJOR}.${MINOR}.$((PATCH+1))"
          yq -i ".version = \"${NEXT}\"" Chart.yaml
          # opcional: sync appVersion
          # yq -i ".appVersion = \"v${NEXT}\"" Chart.yaml
          echo "CHART_VERSION=${NEXT}" >> "$GITHUB_ENV"
          echo "Chart bumped to ${NEXT}"

      - name: Package Helm Chart
        id: pkg
        shell: bash
        run: |
          set -euxo pipefail
          helm package "$CHART_DIR" -d "$GITHUB_WORKSPACE"
          PKG_PATH="$(ls -1t "$GITHUB_WORKSPACE"/*.tgz | head -n 1)"
          test -f "$PKG_PATH"
          echo "CHART_PKG=$PKG_PATH" >> "$GITHUB_ENV"
          echo "Empaquetado: $PKG_PATH"

      - name: Prepare clean main in helm-chart
        shell: bash
        run: |
          set -euxo pipefail
          cd helm-chart
          git fetch --all
          git checkout "${HELM_PAGES_BRANCH}"
          git reset --hard "origin/${HELM_PAGES_BRANCH}"
          git clean -fdx

      - name: Copy packaged chart to helm-chart repo
        shell: bash
        run: |
          set -euxo pipefail
          cp "${CHART_PKG}" helm-chart/
          ls -lah helm-chart

      - name: Update Helm repo index (merge)
        shell: bash
        run: |
          set -euxo pipefail
          cd helm-chart
          if [ -f index.yaml ]; then
            helm repo index . --url "${HELM_REPO_URL}" --merge index.yaml
          else
            helm repo index . --url "${HELM_REPO_URL}"
          fi
          head -n 40 index.yaml

      - name: Commit and push (force remote with PAT)
        shell: bash
        env:
          PAT_USER: ${{ secrets.PAT_HELMCHART_USER }}
        run: |
          set -euxo pipefail
          cd helm-chart
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish chart ${HELM_CHART_NAME} ${CHART_VERSION}" || echo "No commit needed"
          git remote set-url origin "https://${PAT_USER}:${HELM_PAT}@github.com/${HELM_PAGES_REPO}.git"
          git push origin "${HELM_PAGES_BRANCH}"
