name: Package & Publish Helm (in manifests repo, subfolder helm-chart)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package_publish:
    runs-on: ubuntu-latest

    env:
      HELM_CHART_DIR: charts/pedido-app          # ruta del chart
      HELM_CHART_NAME: pedido-app                # nombre del chart
      HELM_REPO_SUBDIR: helm-chart               # carpeta donde se publican .tgz + index.yaml
      HELM_REPO_URL: https://ritatrcr.github.io/manifiestos-delivery-app/helm-chart/  # URL pública de esa carpeta en Pages

    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_HELMCHART }}
          persist-credentials: false  # importante para no usar GITHUB_TOKEN por defecto

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install yq
        shell: bash
        run: |
          set -euxo pipefail
          YQ_VERSION=v4.44.3
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          helm version && yq --version

      # ====== LINT & PACKAGE ======
      - name: Lint chart
        shell: bash
        run: |
          set -euxo pipefail
          cd "${HELM_CHART_DIR}"
          helm lint .

      - name: Package chart into helm-chart/ subfolder
        id: pkg
        shell: bash
        run: |
          set -euxo pipefail
          # Asegura la carpeta de publicación
          mkdir -p "${HELM_REPO_SUBDIR}"

          # Empaqueta el chart directamente dentro de helm-chart/
          cd "${HELM_CHART_DIR}"
          helm package . -d "$GITHUB_WORKSPACE/${HELM_REPO_SUBDIR}"

          # Detecta el tgz recién creado
          PKG_PATH="$(ls -1t "$GITHUB_WORKSPACE/${HELM_REPO_SUBDIR}/${HELM_CHART_NAME}-"*.tgz | head -n 1)"
          test -f "$PKG_PATH"
          echo "PKG_PATH=$PKG_PATH" >> "$GITHUB_OUTPUT"
          echo "PKG_PATH=$PKG_PATH"

          # Extrae versión del nombre de archivo: pedido-app-<VERSION>.tgz -> <VERSION>
          PKG_FILE="$(basename "$PKG_PATH")"
          CHART_VERSION="${PKG_FILE#${HELM_CHART_NAME}-}"
          CHART_VERSION="${CHART_VERSION%.tgz}"
          echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=$CHART_VERSION"

      - name: Assert values-dev/prod inside tgz
        shell: bash
        run: |
          set -euxo pipefail
          tar -tzf "${{ steps.pkg.outputs.PKG_PATH }}" | grep -E 'values-(dev|prod)\.yaml'

      # ====== INDEX (merge) dentro de helm-chart/ ======
      - name: Update Helm repo index (in subfolder)
        shell: bash
        run: |
          set -euxo pipefail
          cd "${HELM_REPO_SUBDIR}"
          if [ -f index.yaml ]; then
            helm repo index . --url "${HELM_REPO_URL}" --merge index.yaml
          else
            helm repo index . --url "${HELM_REPO_URL}"
          fi
          echo "==== index.yaml (head) ===="
          head -n 20 index.yaml
          echo "==== paquetes ===="
          ls -lh *.tgz

      # ====== COMMIT & PUSH ======
      - name: Commit & push changes (with PAT)
        shell: bash
        env:
          PAT_USER: ritatrcr
          PAT_TOKEN: ${{ secrets.PAT_HELMCHART }}       
        run: |
          set -euxo pipefail
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add "${HELM_REPO_SUBDIR}/${HELM_CHART_NAME}-"*.tgz "${HELM_REPO_SUBDIR}/index.yaml"
          git commit -m "Publish chart ${HELM_CHART_NAME} ${{ steps.pkg.outputs.CHART_VERSION }}" || echo "No commit needed"
          # Fuerza el remoto con usuario+PAT (evita 403)
          git remote set-url origin "https://${PAT_USER}:${PAT_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin main
