name: Package & Publish Helm (to helm-chart repo + GitHub Pages)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package_publish:
    runs-on: ubuntu-latest

    env:
      # === Chart origen (en este repo) ===
      HELM_CHART_DIR: charts/pedido-app
      HELM_CHART_NAME: pedido-app

      # === Repo de destino (Pages) ===
      HELM_PAGES_REPO: ritatrcr/helm-chart
      HELM_PAGES_BRANCH: main
      HELM_REPO_URL: https://ritatrcr.github.io/helm-chart/   # URL pública de Pages

    steps:
      # 1) Checkout del repo donde está el chart (este repo)
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # evitamos que quede el GITHUB_TOKEN por defecto

      # 2) Checkout del repo de Pages (destino)
      - name: Checkout helm-chart repo (Pages)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.HELM_PAGES_REPO }}
          ref: ${{ env.HELM_PAGES_BRANCH }}
          path: helm-pages
          token: ${{ secrets.PAT_HELMCHART }}
          persist-credentials: false

      # 3) Herramientas
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install yq
        shell: bash
        run: |
          set -euxo pipefail
          YQ_VERSION=v4.44.3
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          helm version && yq --version

      # 4) Lint del chart
      - name: Lint chart
        shell: bash
        run: |
          set -euxo pipefail
          cd "${HELM_CHART_DIR}"
          helm lint .

      # 5) Preparar árbol limpio en el repo de Pages (evita unstaged changes)
      - name: Prepare clean main in helm-chart repo
        shell: bash
        run: |
          set -euxo pipefail
          cd helm-pages
          git fetch --all
          git checkout "${HELM_PAGES_BRANCH}"
          git reset --hard "origin/${HELM_PAGES_BRANCH}"
          git clean -fdx
          git status

      # 6) Empaquetar el chart directamente dentro del repo de Pages
      - name: Package chart into helm-pages/
        id: pkg
        shell: bash
        run: |
          set -euxo pipefail
          cd "${HELM_CHART_DIR}"
          helm package . -d "$GITHUB_WORKSPACE/helm-pages"

          # Detectar el tgz recién creado
          PKG_PATH="$(ls -1t "$GITHUB_WORKSPACE/helm-pages/${HELM_CHART_NAME}-"*.tgz | head -n 1)"
          test -f "$PKG_PATH"
          echo "PKG_PATH=$PKG_PATH" >> "$GITHUB_OUTPUT"
          echo "PKG_PATH=$PKG_PATH"

          # Extraer versión desde el nombre: pedido-app-<VERSION>.tgz -> <VERSION>
          PKG_FILE="$(basename "$PKG_PATH")"
          CHART_VERSION="${PKG_FILE#${HELM_CHART_NAME}-}"
          CHART_VERSION="${CHART_VERSION%.tgz}"
          echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=$CHART_VERSION"

      # 7) Verificar que values-dev/prod están dentro del .tgz
      - name: Assert values-dev/prod inside tgz
        shell: bash
        run: |
          set -euxo pipefail
          tar -tzf "${{ steps.pkg.outputs.PKG_PATH }}" | grep -E 'values-(dev|prod)\.yaml'

      # 8) Generar/actualizar index.yaml (merge) en el repo de Pages
      - name: Update Helm repo index (merge) in helm-pages
        shell: bash
        run: |
          set -euxo pipefail
          cd helm-pages
          if [ -f index.yaml ]; then
            helm repo index . --url "${HELM_REPO_URL}" --merge index.yaml
          else
            helm repo index . --url "${HELM_REPO_URL}"
          fi
          echo "==== index.yaml (head) ===="
          head -n 20 index.yaml
          echo "==== paquetes ===="
          ls -lh *.tgz

      # 9) Commit & push al repo de Pages usando PAT (evita 403)
      - name: Commit & push changes (to helm-chart repo)
        shell: bash
        env:
          PAT_USER: ritatrcr   # ej: ritatrcr
          PAT_TOKEN: ${{ secrets.PAT_HELMCHART }}       # PAT con Contents: Read/Write
        run: |
          set -euxo pipefail
          cd helm-pages
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Publish chart ${HELM_CHART_NAME} ${{ steps.pkg.outputs.CHART_VERSION }}" || echo "No commit needed"
          git remote set-url origin "https://${PAT_USER}:${PAT_TOKEN}@github.com/${{ env.HELM_PAGES_REPO }}.git"
          git push origin "${HELM_PAGES_BRANCH}"
